/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wetterstation;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.List;

class AppTest {

    private WetterStation init() {
        final WetterStation station = new WetterStation();
        station.addTag(8);
        station.addTag(10);
        station.addTag(4);
        station.addTag(8);
        station.addTag(12);
        station.addTag(14);
        station.addTag(14);
        station.addTag(16);
        station.addTag(17);
        station.addTag(7);
        return station;
    }

    @Test
    void testTage() {
        final WetterStation station = init();

        List<Tag> tage = station.getTage();
        assertEquals(10, tage.size());

        assertEquals(1, tage.get(0).getTagImMonat());
        assertEquals(2, tage.get(1).getTagImMonat());
        assertEquals(3, tage.get(2).getTagImMonat());
        assertEquals(4, tage.get(3).getTagImMonat());
        assertEquals(5, tage.get(4).getTagImMonat());
        assertEquals(6, tage.get(5).getTagImMonat());
        assertEquals(7, tage.get(6).getTagImMonat());
        assertEquals(8, tage.get(7).getTagImMonat());
        assertEquals(9, tage.get(8).getTagImMonat());
        assertEquals(10, tage.get(9).getTagImMonat());

        assertEquals(8, tage.get(0).getTemperatur());
        assertEquals(10, tage.get(1).getTemperatur());
        assertEquals(4, tage.get(2).getTemperatur());
        assertEquals(8, tage.get(3).getTemperatur());
        assertEquals(12, tage.get(4).getTemperatur());
        assertEquals(14, tage.get(5).getTemperatur());
        assertEquals(14, tage.get(6).getTemperatur());
        assertEquals(16, tage.get(7).getTemperatur());
        assertEquals(17, tage.get(8).getTemperatur());
        assertEquals(7, tage.get(9).getTemperatur());
    }

    @Test
    void testMin() {
        assertEquals(4, init().getMin());
    }

    @Test
    void testMax() {
        assertEquals(17, init().getMax());
    }

    @Test
    void testDurchschnitt() {
        assertEquals(11, init().getDurchschnitt());
    }

    @Test
    void testToString() {
        assertEquals(
            "Temp:\t8\t10\t4\t8\t12\t14\t14\t16\t17\t7\n"
            +"Tag: \t1\t2\t3\t4\t5\t6\t7\t8\t9\t10"
            , init().toString());
    }
}
