/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wetterstation;

public class App {
   
    public static void main(String[] args) {
        
        final WetterStation station = new WetterStation();
        station.addTag(8);
        station.addTag(10);
        station.addTag(4);
        station.addTag(8);
        station.addTag(12);
        station.addTag(14);
        station.addTag(14);
        station.addTag(16);
        station.addTag(17);
        station.addTag(7);
        System.out.println(station);

    }
}
