# Autoquartett
:icons: font

## Teil 1

### Klassen, Attribute und Objekte

Beispiel:

[plantuml]
....

class Auto {
  Hersteller
  Bezeichnung
  Preis
  Hubraum
  Leistung
  Beschleunigung
  Geschwindigkeit
  Verbrauch
}

object "Porsche GT3" as porsche {
  Hersteller: Porsche
  Bezeichnung: GT3
  Preis: 121.100
  Hubraum: 3600
  Leistung: 381
  Beschleunigung: 4,4
  Geschwindigkeit: 306
  Verbrauch: 9,8
}

object "Trabant 601" as trabbi {
  Hersteller: Trabbant
  Bezeichnung: 601 Universal
  Preis: 9.900
  Hubraum: 595
  Leistung: 26
  Beschleunigung: 666
  Geschwindigkeit: 100
  Verbrauch: 8,5
}

Auto <|-- porsche
Auto <|-- trabbi

....

[source,java]
----
class Auto { <1>
   String hersteller; <2>

   // ...
}

void main(){

    Auto porschegt3 = new Auto(); <3>
    porsche.hersteller = "Porsche"; <4>

    // ...
}

----
<1> Definition der Klasse `Auto`
<2> Definition des Attrbiutes `hersteller`
<3> Erzeugung eines neuen Objektes der Klasse Auto
<4> Setzen des Attributes `hersteller`

### Aufgabe 1

1. Erstelle die Klasse Auto mit den Attributen des Diagrammes.
2. Erzeuge 2 Objekte "porsche" und "trabbi" uns setze die Attribute der Objekte auf die jeweiligen Werte

## Teil 2

### Spieler

[plantuml]
....
class Spieler {
  name: String
  autos: List<Auto>
}
....

### Aufgabe 1

1. Erzeuge 2 Spieler-Objekte.
2. Weise dem ersten Spieler die hälfte der Autos zu und dem zweiten Spieler die andere Hälfte.

### Methoden

[plantuml]
....
class Spieler {
  name: String
  autos: List<Auto>

  hatAutos() : bool
}
....

### Aufgabe 2

1. Schreibe eine Funktion hatAutos die den Wert true zurückliefert wenn des Spieler Ojekt noch über mindestens ein Auto in der Liste verfügt
2. Prüfe ob Spieler 2 ein auto hat und gib die Information auf dem Terminal aus

## Teil 3

[plantuml]
....
class Spieler {
  name: String
  autos: List<Auto>

  hatAutos() : bool
  nimmObersteAuto() : Auto
  fuegeAutoZuDeckHinzu(Auto)
}

note right of Spieler::nimmObersteAuto
  Auto am Anfang des Decks
  entfernen und zurückliefern
end note

note right of Spieler::fuegeAutoZuDeckHinzu
  Auto am Ende des Decks hinzufügen
end note

....

### Aufgabe 1

1. Erweitere Spieler um Funktionen
2. Führe eine Spielrunde Durch:
   a. Nimm jeweils das oberste Auto jedes Spielers
   b. Gib Hersteller/Name auf Terminal aus
   c. Vergleiche die Werte von Verbrauch
   d. Gib Details und Gewinner auf Terminal aus
   e. Füge beide Karten dem Deck des Gewinners hinzu
   f. Prüfe ob fer Verlierer noch Karten besitzt und gib Ergebnis auf Terminal aus

## Teil 4

### Aufgabe 1

1. Füge deinem Spiel weitere Autos hinzu
2. Lasse das Spiel so lange laufen bis ein Spieler keine Karten mehr besitzt

### Aufgabe 2

1. Erweitere Prüfung um andere Attribute
2. Lass Spieler 1 durch Eingabe des Benutzers das zu Prüfende Attribut wählen
3. Lass Spieler 2 durch "Computer" (Zufall) das zu prüfende Attribut wählen

## Teil 5

### Setter und Getter

[source,java]
----
class Auto {
   private String hersteller; <1>

   public void setHersteller(String hersteller) { <2>
       this.hersteller = hersteller;
   }

   public String getHersteller() { <3>
       return this.hersteller;
   }
}
----
<1> Privates Attribut, dass nur innerhalb der Klasse direkt angesprochen werden kann
<2> Setter zum setzen des Attributes
<3> Getter zum auslesen des Attributes

### Aufgabe 1

1. Verbiete direkten Zugriff auf die Attribute aller Klassen
2. Ersetze direkten Zugriff auf die Attribute durch Setter und Getter Aufrufe

### Constructor

[source,java]
----
class Auto {
   private final String hersteller; <1>

   public Auto(String hersteller) { <2>
        this.hersteller = hersteller;
   }
}
----
<1> Attribut ist `final` und muss direkt oder im Constructor gesetzt werden
<2> Constructor für Klasse Auto in dem das Attribut Hersteller beim Erzeugen des Objekte gesetzt wird

### Aufgabe 2

1. Erszeuge Constructoren für alle Klassen
2. Mache alle Attribute, die nach dem Erzeugen eines Objektes nicht mehr verändert werden müssen `final`

